Repository Team1MediaApp/MediaApp, pull requests merged in 2023-10, with the labels that each got.

#20 [Feature] HomeFragment CategoryList Spinner Add / Trending Auto Scroll
  app/build.gradle.kts
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/java/com/example/mediaapp/util/CategoryId.kt
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/values/arrays.xml
Labels: feature, add, fix

#21 Feature/detailpage
  app/build.gradle.kts
  app/src/main/java/com/example/mediaapp/ChannelDetailFragment.kt
  app/src/main/java/com/example/mediaapp/DetailFragment.kt
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/java/com/example/mediaapp/MainActivity.kt
  app/src/main/java/com/example/mediaapp/MypageDialogModifyFragment.kt
  app/src/main/java/com/example/mediaapp/data/model/channel/ChItem.kt
  app/src/main/java/com/example/mediaapp/data/model/video/Item.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/DifferCallback.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeCategoryRcvAdapter.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeChannelRcvAdapter.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeTrendingRcvAdapter.kt
  app/src/main/res/anim/anim.xml
  app/src/main/res/anim/anim_left.xml
  app/src/main/res/anim/anim_left_exit.xml
  app/src/main/res/anim/anim_right.xml
  app/src/main/res/anim/anim_right_exit.xml
  app/src/main/res/layout/channel_detail_fragment.xml
  app/src/main/res/layout/detail_fragment.xml
  app/src/main/res/layout/home_rcv_item_trending.xml
Labels: feature, add

#24 [Fix] Spinner lifecycle fix
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
Labels: fix

#29 [Feature] Detailpage SharedPreferences 구현
  app/src/main/java/com/example/mediaapp/ChannelDetailFragment.kt
  app/src/main/java/com/example/mediaapp/DetailFragment.kt
  app/src/main/java/com/example/mediaapp/MainActivity.kt
  app/src/main/java/com/example/mediaapp/MypageFragment.kt
  app/src/main/res/layout/channel_detail_fragment.xml
  app/src/main/res/layout/detail_fragment.xml
Labels: feature, add

#32 [Feature] Category RecyclerView Infinity Scroll Feature
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/java/com/example/mediaapp/SearchViewModel.kt
  app/src/main/java/com/example/mediaapp/VideoRepository.kt
  app/src/main/java/com/example/mediaapp/VideoRepositoryImpl.kt
  app/src/main/java/com/example/mediaapp/data/api/VideoInterface.kt
  app/src/main/res/layout/home_rcv_item_channel.xml
Labels: feature, add

#34 [Fix] SharedPreferences 중복 정보전달로 인한 수정
  app/src/main/java/com/example/mediaapp/util/Util.kt
Labels: feature, fix

#37 [Feature] Screen View Orientation
  app/src/main/AndroidManifest.xml
Labels: add

#38 [Fix] 더미값으로 Category 리스트 infinityScroll 검색하는 부분 Spinner의 값을 받는걸로 수정
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
Labels: fix

#39 [Feature]popanimation
  app/src/main/java/com/example/mediaapp/DetailFragment.kt
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/res/layout/detail_fragment.xml
Labels: feature, fix

#40 [UI] DetailFragment UI fix
  app/src/main/java/com/example/mediaapp/DetailFragment.kt
  app/src/main/java/com/example/mediaapp/MypageMyItemAdapter.kt
  app/src/main/java/com/example/mediaapp/data/api/SearchRepository.kt
  app/src/main/java/com/example/mediaapp/data/api/SearchRepositoryImpl.kt
  app/src/main/java/com/example/mediaapp/data/api/YoutubeService.kt
  app/src/main/java/com/example/mediaapp/data/model/video/Snippet.kt
  app/src/main/java/com/example/mediaapp/data/model/video/Thumbnails.kt
  app/src/main/java/com/example/mediaapp/detail/VideoServiceInterface.kt
  app/src/main/java/com/example/mediaapp/detail/YoutubeDetailModel.kt
  app/src/main/java/com/example/mediaapp/model/YoutubeChannelResponse.kt
  app/src/main/res/drawable/detail_channel_shape.xml
  app/src/main/res/drawable/detail_img_full_bookmark.xml
  app/src/main/res/drawable/detail_img_line_bookmark.xml
  app/src/main/res/drawable/detail_img_movie.png
  app/src/main/res/drawable/detail_img_share.xml
  app/src/main/res/layout/detail_fragment.xml
Labels: UI, fix

#41 [Feature] get channel api data
  app/src/main/java/com/example/mediaapp/DetailFragment.kt
  app/src/main/java/com/example/mediaapp/data/api/SearchRepositoryImpl.kt
Labels: feature, add

#43 [UI] 디테일 구독자 수 형태 변경
  app/src/main/java/com/example/mediaapp/DetailFragment.kt
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeChannelRcvAdapter.kt
Labels: UI, add

#45 UI/fix
  app/src/main/res/drawable/home_spinner_shape.xml
  app/src/main/res/layout/detail_fragment.xml
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/home_rcv_item_category.xml
  app/src/main/res/layout/home_rcv_item_channel.xml
  app/src/main/res/layout/mypage_fragment.xml
  app/src/main/res/layout/mypage_item.xml
  app/src/main/res/layout/mypage_rcv_item_view.xml
  app/src/main/res/values/arrays.xml
Labels: UI, fix
