Repository Team1MediaApp/MediaApp, pull requests merged in 2023-09, with the labels that each got.

#1 [Feature] GitIgnore 추가
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
Labels: feature

#2 [UI] Detailpage
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mediaapp/MainActivity.kt
  app/src/main/res/drawable/detail_btn_back.xml
  app/src/main/res/drawable/detail_img_thumnail.png
  app/src/main/res/drawable/main_bottom_navigation_home.xml
  app/src/main/res/drawable/main_bottom_navigation_person.xml
  app/src/main/res/drawable/main_bottom_navigation_search.xml
  app/src/main/res/drawable/menu_selector.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: UI

#4 [UI] HomeFragment
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/res/drawable/img_home_trending_sample1.jpg
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/home_rcv_item_view.xml
  app/src/main/res/values/colors.xml
Labels: UI

#3 [UI] SearchFragment
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/search_channel_item.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/search_video_item.xml
  app/src/main/res/values/strings.xml
Labels: UI, add, nomerge

#10 [UI]mypage
  app/src/main/java/com/example/mediaapp/MypageDialogModifyFragment.kt
  app/src/main/java/com/example/mediaapp/MypageFragment.kt
  app/src/main/java/com/example/mediaapp/Mypage_Fragment.kt
  app/src/main/res/drawable/kit_mypage_profile_image_circle.xml
  app/src/main/res/drawable/kit_mypagemodify_edittext_box.xml
  app/src/main/res/drawable/kit_mypagemodify_save_button.xml
  app/src/main/res/drawable/mypage_arrowdown.png
  app/src/main/res/drawable/mypage_backgroundprofile.jpg
  app/src/main/res/drawable/mypage_bell.png
  app/src/main/res/drawable/mypage_button_off.png
  app/src/main/res/drawable/mypage_button_on.png
  app/src/main/res/drawable/mypage_pen.png
  app/src/main/res/drawable/mypage_profile.png
  app/src/main/res/drawable/mypagemodify_changeimage.png
  app/src/main/res/drawable/mypagemodify_profile.png
  app/src/main/res/drawable/mypagemodify_save.png
  app/src/main/res/drawable/mypagemodify_x.png
  app/src/main/res/layout/main_activity.xml
  app/src/main/res/layout/mypage_dialog_modify_fragment.xml
  app/src/main/res/layout/mypage_fragment.xml
Labels: add, fix

#12 [Feature] Retrofit, OkHttp3 Gson Convert를 통해 Youtube API - Videos:List 데이터 가져오기.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/mediaapp/Constants.kt
  app/src/main/java/com/example/mediaapp/DetailFragment.kt
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/java/com/example/mediaapp/MainActivity.kt
  app/src/main/java/com/example/mediaapp/SearchViewModel.kt
  app/src/main/java/com/example/mediaapp/SearchViewModelProviderFactory.kt
  app/src/main/java/com/example/mediaapp/VideoRepository.kt
  app/src/main/java/com/example/mediaapp/VideoRepositoryImpl.kt
  app/src/main/java/com/example/mediaapp/data/api/RetrofitInstance.kt
  app/src/main/java/com/example/mediaapp/data/api/VideoInterface.kt
  app/src/main/java/com/example/mediaapp/data/model/video/Id.kt
  app/src/main/java/com/example/mediaapp/data/model/video/Item.kt
  app/src/main/java/com/example/mediaapp/data/model/video/SearchResponse.kt
  app/src/main/java/com/example/mediaapp/data/model/video/Snippet.kt
  app/src/main/java/com/example/mediaapp/data/model/video/Thumbnails.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/home_rcv_item_view.xml
Labels: feature, add, nomerge

#13 [Feature] search call api
  app/build.gradle.kts
  app/src/main/java/com/example/mediaapp/DetailFragment.kt
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/java/com/example/mediaapp/NetworkClient.kt
  app/src/main/java/com/example/mediaapp/NetworkRepository.kt
  app/src/main/java/com/example/mediaapp/SearchFragment.kt
  app/src/main/java/com/example/mediaapp/SearchListAdapter.kt
  app/src/main/java/com/example/mediaapp/YoutubeService.kt
  app/src/main/java/com/example/mediaapp/model/YoutubeSearchModel.kt
  app/src/main/res/layout/search_fragment.xml
Labels: feature, add

#15 [Feature] add trending top10 recyclerView
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/java/com/example/mediaapp/SearchViewModel.kt
  app/src/main/java/com/example/mediaapp/data/api/RetrofitInstance.kt
  app/src/main/java/com/example/mediaapp/data/model/video/CategoryId.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/DifferCallback.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeCategoryRcvAdapter.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeRecyclerViewAdapter.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeTrendingRcvAdapter.kt
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/home_rcv_item_category.xml
  app/src/main/res/layout/home_rcv_item_trending.xml
  app/src/main/res/values/arrays.xml
Labels: feature, add

#16 [UI&Feature] HomeFragment Category, Channel rcv add
  app/src/main/java/com/example/mediaapp/Constants.kt
  app/src/main/java/com/example/mediaapp/HomeFragment.kt
  app/src/main/java/com/example/mediaapp/SearchViewModel.kt
  app/src/main/java/com/example/mediaapp/VideoRepository.kt
  app/src/main/java/com/example/mediaapp/VideoRepositoryImpl.kt
  app/src/main/java/com/example/mediaapp/data/api/RetrofitInstance.kt
  app/src/main/java/com/example/mediaapp/data/api/VideoInterface.kt
  app/src/main/java/com/example/mediaapp/data/model/channel/ChItem.kt
  app/src/main/java/com/example/mediaapp/data/model/channel/ChSnippet.kt
  app/src/main/java/com/example/mediaapp/data/model/channel/ChThumbnails.kt
  app/src/main/java/com/example/mediaapp/data/model/channel/ChannelResponse.kt
  app/src/main/java/com/example/mediaapp/data/model/video/CategoryId.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/DifferCallback.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeCategoryRcvAdapter.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeChannelRcvAdapter.kt
  app/src/main/java/com/example/mediaapp/ui/adapter/HomeTrendingRcvAdapter.kt
  app/src/main/java/com/example/mediaapp/util/CategoryId.kt
  app/src/main/java/com/example/mediaapp/util/Constants.kt
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/home_rcv_item_category.xml
  app/src/main/res/layout/home_rcv_item_channel.xml
Labels: feature, UI, add, fix
